name: Main

on:
  push:
  schedule:
  - cron: "30 17 15 * *"
permissions: {}
env:
  ARTIFACT: website-janitor

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJSON(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJSON(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJSON(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJSON(matrix) }}
      run: echo "$MATRIX_CONTEXT"
    - name: Dump environment variables
      run: set
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_version: ${{ steps.output.outputs.new_version }}
      build_timestamp: ${{ steps.output.outputs.build_timestamp }}
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        persist-credentials: true
    - name: Bump version and push tag
      id: tag
      if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
      uses: ArloL/calver-tag-action@7598d5f992d9a747726f203295b010fa2705a83d # v2511.0.107
    - id: output
      env:
        NEW_VERSION: ${{ steps.tag.outputs.new_version }}
      run: |
        echo "new_version=${NEW_VERSION:-$GITHUB_SHA}" >> "${GITHUB_OUTPUT}"
        echo "build_timestamp=$(date --iso-8601=seconds)" >> "${GITHUB_OUTPUT}"
    - name: Make sure build did not change anything
      run: git diff --exit-code
  macos:
    needs: version
    runs-on: macos-latest
    env:
      REVISION: ${{ needs.version.outputs.new_version }}
      BUILD_TIMESTAMP: ${{ needs.version.outputs.build_timestamp }}
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        persist-credentials: false
    - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
      with:
        cache: maven
        distribution: temurin
        java-version-file: .tool-versions
    - name: Build with Maven
      run: |
        set -o xtrace
        ./mvnw \
          --batch-mode \
          -Dsha1="${GITHUB_SHA}" \
          -Drevision="${REVISION}" \
          verify
    - name: Move artifacts
      run: |
        mkdir target/artifacts
        cp target/${{ env.ARTIFACT }}-* target/artifacts
    - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: ${{ env.ARTIFACT }}-${{ github.job }}-${{ needs.version.outputs.new_version }}
        path: target/artifacts
    - name: Make sure build did not change anything
      run: git diff --exit-code
  linux:
    needs: version
    runs-on: ubuntu-latest
    env:
      REVISION: ${{ needs.version.outputs.new_version }}
      BUILD_TIMESTAMP: ${{ needs.version.outputs.build_timestamp }}
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        persist-credentials: false
    - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
      with:
        cache: maven
        distribution: temurin
        java-version-file: .tool-versions
    - name: Build with Maven
      run: |
        set -o xtrace
        ./mvnw \
          --batch-mode \
          -Dsha1="${GITHUB_SHA}" \
          -Drevision="${REVISION}" \
          verify
    - name: Move artifacts
      run: |
        mkdir target/artifacts
        cp target/${{ env.ARTIFACT }}-* target/artifacts
    - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: ${{ env.ARTIFACT }}-${{ github.job }}-${{ needs.version.outputs.new_version }}
        path: target/artifacts
    - name: Make sure build did not change anything
      run: git diff --exit-code
  windows:
    needs: version
    runs-on: windows-latest
    env:
      USER: runner
      REVISION: ${{ needs.version.outputs.new_version }}
      BUILD_TIMESTAMP: ${{ needs.version.outputs.build_timestamp }}
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        persist-credentials: false
    - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
      with:
        cache: maven
        distribution: temurin
        java-version-file: .tool-versions
    - name: Build with Maven
      run: |
        .\mvnw --batch-mode -Dsha1="$env:GITHUB_SHA" -Drevision="$env:REVISION" verify
    - name: Move artifacts
      run: |
        mkdir target/artifacts
        copy target/${{ env.ARTIFACT }}-* target/artifacts
    - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: ${{ env.ARTIFACT }}-${{ github.job }}-${{ needs.version.outputs.new_version }}
        path: target/artifacts
    - name: Make sure build did not change anything
      run: git diff --exit-code
  release:
    needs:
    - version
    - macos
    - linux
    - windows
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        persist-credentials: false
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
      with:
        path: ./target
    - name: Zip artifacts
      working-directory: target
      env:
        NEW_VERSION: ${{ needs.version.outputs.new_version }}
      run: |
        zip -r windows.zip "${ARTIFACT}-windows-${NEW_VERSION}/"
        zip -r linux.zip "${ARTIFACT}-linux-${NEW_VERSION}/"
        zip -r macos.zip "${ARTIFACT}-macos-${NEW_VERSION}/"
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
      with:
        draft: true
        name: Release ${{ needs.version.outputs.new_version }}
        tag: v${{ needs.version.outputs.new_version }}
    - name: Upload Release Asset
      uses: shogo82148/actions-upload-release-asset@59cbc563d11314e48122193f8fe5cdda62ea6cf9 # v1.9.1
      with:
        asset_content_type: application/zip
        asset_name: ${{ env.ARTIFACT }}-linux-${{ needs.version.outputs.new_version }}.zip
        asset_path: ./target/linux.zip
        upload_url: ${{ steps.create_release.outputs.upload_url }}
    - name: Upload Release Asset
      uses: shogo82148/actions-upload-release-asset@59cbc563d11314e48122193f8fe5cdda62ea6cf9 # v1.9.1
      with:
        asset_content_type: application/zip
        asset_name: ${{ env.ARTIFACT }}-windows-${{ needs.version.outputs.new_version }}.zip
        asset_path: ./target/windows.zip
        upload_url: ${{ steps.create_release.outputs.upload_url }}
    - name: Upload Release Asset
      uses: shogo82148/actions-upload-release-asset@59cbc563d11314e48122193f8fe5cdda62ea6cf9 # v1.9.1
      with:
        asset_content_type: application/zip
        asset_name: ${{ env.ARTIFACT }}-macos-${{ needs.version.outputs.new_version }}.zip
        asset_path: ./target/macos.zip
        upload_url: ${{ steps.create_release.outputs.upload_url }}
    - uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
      with:
        allowUpdates: true
        immutableCreate: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        tag: v${{ needs.version.outputs.new_version }}
        updateOnlyUnreleased: true
    - name: Make sure build did not change anything
      run: git diff --exit-code
  deploy:
    needs:
    - version
    - macos
    - linux
    - windows
    if: ${{ github.event_name == 'push' && !startsWith(github.ref, 'refs/heads/dependabot/') }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        persist-credentials: false
    - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
      with:
        cache: maven
        distribution: temurin
        java-version-file: .tool-versions
    - name: Publish to GitHub Packages Apache Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REVISION: ${{ needs.version.outputs.new_version }}
        BUILD_TIMESTAMP: ${{ needs.version.outputs.build_timestamp }}
      run: |
        ./mvnw \
          --batch-mode \
          -Dsha1="${GITHUB_SHA}" \
          -Drevision="${REVISION}" \
          -DaltDeploymentRepository="github::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY}" \
          deploy
    - name: Make sure build did not change anything
      run: git diff --exit-code
  required-status-check:
    name: main.required-status-check
    needs:
    - macos
    - linux
    - windows
    # GitHub Actions skips this job when any of the dependents fail. And skips
    # are considered success in their weird logic. So we always run it and fail
    # ourselves if necessary
    if: always()
    runs-on: ubuntu-latest
    steps:
    - run: echo "Use this job as the required status check of this workflow"
    - name: Check that all jobs were successful
      env:
        RESULTS: ${{ toJSON(needs) }}
      run: |
        echo "$RESULTS" | jq --exit-status 'all(.result == "success")' || exit 1
